import utilities.api.item_ids as ids

# potion recipes
potion_recipes = {
    "Guam Potion": [["Guam_leaf_bank.png", "vial_of_water.png"],
                    [ids.GUAM_LEAF, ids.VIAL_OF_WATER]],
    "Attack Potion": [["Guam_potion_(unf)_bank.png", "Eye_of_newt_bank.png"],
                      [ids.GUAM_POTION_UNF, ids.EYE_OF_NEWT]],
    "Marrentill Potion": [["Marrentill.png", "vial_of_water.png"],
                          [ids.MARRENTILL, ids.VIAL_OF_WATER]],
    "Rouge's Purse": [["Rogue's_purse_bank.png", "vial_of_water.png"],
                      [ids.ROGUES_PURSE, ids.VIAL_OF_WATER]],
    "Avantoe Potion": [["Avantoe_bank.png", "vial_of_water.png"],
                       [ids.AVANTOE, ids.VIAL_OF_WATER]],
    "Cadantine Potion": [["Cadantine_bank.png", "vial_of_water.png"],
                         [ids.CADANTINE, ids.VIAL_OF_WATER]],
    "Dwarf Weed Potion": [["Dwarf_weed_bank.png", "vial_of_water.png"],
                          [ids.DWARF_WEED, ids.VIAL_OF_WATER]],
    "Harralander Potion": [["Harralander_bank.png", "vial_of_water.png"],
                           [ids.HARRALANDER, ids.VIAL_OF_WATER]],
    "Irit Potion": [["Irit_leaf_bank.png", "vial_of_water.png"],
                    [ids.IRIT_LEAF, ids.VIAL_OF_WATER]],
    "Kwuarm Potion": [["Kwuarm_bank.png", "vial_of_water.png"],
                      [ids.KWUARM, ids.VIAL_OF_WATER]],
    "Lantadyme Potion": [["Lantadyme_bank.png", "vial_of_water.png"],
                         [ids.LANTADYME, ids.VIAL_OF_WATER]],
    "Ranarr Potion": [["Ranarr_weed_bank.png", "vial_of_water.png"],
                      [ids.RANARR_WEED, ids.VIAL_OF_WATER]],
    "Snapdragon Potion": [["Snapdragon_bank.png", "vial_of_water.png"],
                          [ids.SNAPDRAGON, ids.VIAL_OF_WATER]],
    "Tarromin Potion": [["Tarromin_bank.png", "vial_of_water.png"],
                        [ids.TARROMIN, ids.VIAL_OF_WATER]],
    "Toadflax Potion": [["Toadflax_bank.png", "vial_of_water.png"],
                        [ids.TOADFLAX, ids.VIAL_OF_WATER]],
    "Tortstol Potion": [["Torstol_bank.png", "vial_of_water.png"],
                        [ids.TORSTOL, ids.VIAL_OF_WATER]],
    "Serum 207 UNF": [["Ashes_bank.png", "vial_of_water.png"],
                      [ids.ASHES, ids.VIAL_OF_WATER]],
    "Antipoison": [["Marrentill_potion_(unf)_bank.png", "Unicorn_horn_dust_bank.png"],
                   [ids.MARRENTILL_POTION_UNF, ids.UNICORN_HORN_DUST]],
    "Relicym's Balm (unf)": [["Rogue's_purse_bank.png", "vial_of_water.png"],
                             [ids.ROGUES_PURSE, ids.VIAL_OF_WATER]],
    # TODO find unfinished potion ID
    "Relicym's Balm": [["Unfinished_potion_(Rogue's_Purse).png", "Snake_weed_bank.png"],  # fix sprite
                       [None, ids.SNAKE_WEED]],
    "Strength Potion": [["Tarromin_potion_(unf)_bank.png", "Limpwurt_root_bank.png"],
                        [ids.TARROMIN_POTION_UNF, ids.LIMPWURT_ROOT]],
    "Serum 207": [["Tarromin_potion_(unf)_bank.png", "Ashes_bank.png"],
                  [ids.TARROMIN_POTION_UNF, ids.ASHES]],
    "Compost Potion": [["Harralander_potion_(unf)_bank.png", "Volcanic_ash_bank.png"],
                       [ids.HARRALANDER_POTION_UNF, ids.VOLCANIC_ASH]],
    "Restore Potion": [["Harralander_potion_(unf)_bank.png", "Red_spiders'_eggs_bank.png"],
                       [ids.HARRALANDER_POTION_UNF, ids.RED_SPIDERS_EGGS]],
    "Energy Potion": [["Harralander_potion_(unf)_bank.png", "Chocolate_dust_bank.png"],
                      [ids.HARRALANDER_POTION_UNF, ids.CHOCOLATE_DUST]],
    "Defence Potion": [["Ranarr_potion_(unf)_bank.png", "White_berries_bank.png"],
                       [ids.RANARR_POTION_UNF, ids.WHITE_BERRIES]],
    "Agility Potion": [["Toadflax_potion_(unf)_bank.png", "Toad's_legs_bank.png"],
                       [ids.TOADFLAX_POTION_UNF, ids.TOADS_LEGS]],
    "Combat Potion": [["Harralander_potion_(unf)_bank.png", "Goat_horn_dust_bank.png"],
                      [ids.HARRALANDER, ids.GOAT_HORN_DUST]],
    "Prayer Potion": [["Ranarr_potion_(unf)_bank.png", "Snape_grass_bank.png"],
                      [ids.RANARR_POTION_UNF, ids.SNAPE_GRASS]],
    "Super Attack": [["Irit_potion_(unf)_bank.png", "Eye_of_newt_bank.png"],
                     [ids.IRIT_POTION_UNF, ids.EYE_OF_NEWT]],
    "Super AntiPoison": [["Irit_potion_(unf)_bank.png", "Unicorn_horn_dust_bank.png"],
                         [ids.IRIT_POTION_UNF, ids.UNICORN_HORN_DUST]],
    "Fishing Potion": [["Avantoe_potion_(unf)bank.png", "Snape_grass_bank.png"],
                       [ids.AVANTOE_POTION_UNF, ids.SNAPE_GRASS]],
    "Super Energy": [["Avantoe_potion(unf)bank.png", "Mort_myre_fungus_bank.png"],
                     [ids.AVANTOE_POTION_UNF, ids.MORT_MYRE_FUNGUS]],
    "Hunter Potion": [["Avantoe_potion(unf)bank.png", "Kebbit_teeth_dust_bank.png"],
                      [ids.AVANTOE_POTION_UNF, ids.KEBBIT_TEETH_DUST]],
    "Super Strength": [["Kwuarm_potion(unf)bank.png", "Limpwurt_root_bank.png"],
                       [ids.KWUARM_POTION_UNF, ids.LIMPWURT_ROOT]],
    "Weapon poison": [["Kwuarm_potion(unf)bank.png", "Dragon_scale_dust_bank.png"],
                      [ids.KWUARM_POTION_UNF, ids.DRAGON_SCALE_DUST]],
    "Super Restore": [["Snapdragon_potion(unf)_bank.png", "Red_spiders'eggs_bank.png"],
                      [ids.SNAPDRAGON_POTION_UNF, ids.RED_SPIDERS_EGGS]],
    "Sanfew Serum mix 1": [["Super_restore(4)_bank.png", "Unicorn_horn_dust_bank.png"],
                           [ids.SUPER_RESTORE4, ids.UNICORN_HORN_DUST]],
    "Sanfew Serum mix 2": [["Mixture_-_step_1(4)_bank.png", "Snake_weed_bank.png"],
                           [ids.MIXTURE__STEP_14, ids.SNAKE_WEED]],
    "Sanfew Serum": [["Mixture_-_step_2(4)_bank.png", "Nail_beast_nails_bank.png"],
                     [ids.MIXTURE__STEP_24, ids.NAIL_BEAST_NAILS]],
    "Super Defence": [["Cadantine_potion(unf)bank.png", "White_berries_bank.png"],
                      [ids.CADANTINE_POTION_UNF, ids.WHITE_BERRIES]],
    "Antidote+ (unf)": [["Coconut_milk_bank.png", "Toadflax_bank.png"],
                        [ids.COCONUT_MILK, ids.TOADFLAX]],
    "Antidote+": [["Antidote+_(unf)_bank.png", "Yew_roots_bank.png"],
                  [ids.ANTIDOTE_UNF, ids.YEW_ROOTS]],
    "Antifire Potion": [["Lantadyme_potion(unf)_bank.png", "Dragon_scale_dust_bank.png"],
                        [ids.LANTADYME_POTION_UNF, ids.DRAGON_SCALE_DUST]],
    "Divine Super Attack": [["Super_attack(4)_bank.png", "Crystal_dust_bank.png"],
                            [ids.SUPER_ATTACK4, ids.CRYSTAL_DUST]],
    "Divine Super Defence": [["Super_defence(4)bank.png", "Crystal_dust_bank.png"],
                             [ids.SUPER_DEFENCE4, ids.CRYSTAL_DUST]],
    "Ranging Potion": [["Dwarf_weed_potion(unf)bank.png", "Wine_of_zamorak_bank.png"],
                       [ids.DWARF_WEED_POTION_UNF, ids.WINE_OF_ZAMORAK]],
    "Weapon Poison+ (unf)": [["Coconut_milk_bank.png", "Cactus_spine_bank"],
                             [ids.COCONUT_MILK, ids.CACTUS_SPINE]],
    "Weapon Poison+": [["Weapon_poison+_(unf)_bank.png", "Red_spiders'_eggs_bank.png"],
                       [ids.WEAPON_POISON_UNF, ids.RED_SPIDERS_EGGS]],
    "Divine Ranging Potion": [["Ranging_potion(4)bank.png", "Crystal_dust_bank.png"],
                              [ids.RANGING_POTION4, ids.CRYSTAL_DUST]],
    "Magic Potion": [["Lantadyme_potion(unf)_bank.png", "Potato_cactus_bank.png"],
                     [ids.LANTADYME_POTION_UNF, ids.POTATO_CACTUS]],
    "Stamina Potion": [["Lantadyme_potion_(unf)_bank.png", "Amylase_crystal_5_bank.png"],
                       [ids.SUPER_ENERGY4, ids.AMYLASE_CRYSTAL]],
    "Zamorak Brew": [["Torstol_potion_(unf)_bank.png", "Jangerberries_bank.png"],
                     [ids.TORSTOL_POTION_UNF, ids.JANGERBERRIES]],
    "Divine Magic Potion": [["Magic_potion(4)_bank.png", "Crystal_dust_bank.png"],
                            [ids.MAGIC_POTION4, ids.CRYSTAL_DUST]],
    "Antidote++ (unf)": [["Coconut_milk_bank.png", "Irit_leaf_bank.png"],
                         [ids.COCONUT_MILK, ids.IRIT_LEAF]],
    "Antidote++": [["Antidote++_(unf)_bank.png", "Magic_roots_bank.png"],
                   [ids.ANTIDOTE_UNF, ids.MAGIC_ROOTS]],
    "Candatine Blood Potion (unf)": [["Vial_of_blood_bank.png", "Cadantine_bank.png"],
                                     [ids.VIAL_OF_BLOOD, ids.CADANTINE]],
    "Bastion potion": [["Cadantine_blood_potion_(unf)_bank.png", "Wine_of_zamorak_bank.png"],
                       [ids.CADANTINE_BLOOD_POTION_UNF, ids.WINE_OF_ZAMORAK]],
    "Battlemage potion": [["Cadantine_blood_potion_(unf)_bank.png", "Potato_cactus_bank.png"],
                          [ids.CADANTINE_POTION_UNF, ids.POTATO_CACTUS]],
    "Saradomin Brew": [["Toadflax_potion_(unf)_bank.png", "Crushed_nest_bank.png"],
                       [ids.TOADFLAX_POTION_UNF, ids.CRUSHED_NEST]],
    "Weapon Poison++ (unf)": [["Coconut_milk_bank.png", "Cave_nightshade_bank.png"],
                              [ids.COCONUT_MILK, ids.CAVE_NIGHTSHADE]],
    "Weapon Poison++": [["Weapon_poison++_(unf)_bank.png", "Poison_ivy_berries_bank.png"],
                        [ids.WEAPON_POISON_UNF, ids.POISON_IVY_BERRIES]],
    "Extended Antifire": [["Antifire_potion(4)_bank.png", "Lava_scale_shard_5_bank.png"],
                          [ids.ANTIFIRE_POTION4, ids.LAVA_SCALE_SHARD]],
    "Ancient Brew": [["Dwarf_weed_potion_(unf)_bank.png", "Nihil_dust_bank.png"],
                     [ids.DWARF_WEED_POTION_UNF, ids.NIHIL_DUST]],
    "Divine Bastion Potion": [["Bastion_potion(4)_bank.png", "Crystal_dust_bank.png"],
                              [ids.BASTION_POTION4, ids.CRYSTAL_DUST]],
    "Divine Battlemage Potion": [["Battlemage_potion(4)_bank.png", "Crystal_dust_bank.png"],
                                 [ids.BATTLEMAGE_POTION4, ids.CRYSTAL_DUST]],
    "Anti-Venom": [["Anti-venom(4)_bank.png", "Torstol_bank.png"],
                   [ids.ANTIVENOM4, ids.TORSTOL]],
    "Super Combat": [["Super_attack(4)_bank.png", "Super_defence(4)_bank.png", "Super_strength(4)_bank.png", "Torstol_bank.png"],
                     [ids.SUPER_ATTACK4, ids.SUPER_DEFENCE4, ids.SUPER_STRENGTH4, ids.TORSTOL]],
    # TODO add ancient_ess to the item_id.py file
    "Forgotten Brew": [["Ancient_brew(4)_bank.png", "Ancient_essence.png"],
                       [None, ids.ANCIENT_BREW4]],
    "Super Antifire Potion": [["Antifire_potion(4)_bank.png", "Crushed_superior_dragon_bones_bank.png"],
                              [ids.CRUSHED_SUPERIOR_DRAGON_BONES, ids.ANTIFIRE_POTION4]],
    "Anti-Venom+": [["Anti-venom(4)_bank.png", "Torstol_bank.png"],
                    [ids.ANTIVENOM4_12913, ids.TORSTOL]],
    "Divine Super Combat Potion": [["Super_combat_potion(4)_bank.png", " Crystal_dust_bank.png"],
                                   [ids.CRYSTAL_DUST, ids.SUPER_COMBAT_POTION4]],
    "Extended Super Antifire": [["Super_antifire_potion(4)_bank.png", "Lava_scale_shard_5_bank.png"],
                                [ids.LAVA_SCALE_SHARD, ids.SUPER_ANTIFIRE_POTION4]]}

Potion_names = ["Agility Potion",
                "Ancient Brew",
                "Anti-Venom",
                "Anti-Venom+",
                "Anti-venom+",
                "Antidote++ (unf)",
                "Antidote++",
                "Antipoison",
                "Attack Potion",
                "Avantoe Potion",
                "Bastion potion",
                "Battlemage potion",
                "Cadantine Potion",
                "Candatine Blood Potion (unf)",
                "Combat Potion",
                "Compost Potion",
                "Defence Potion",
                "Divine Bastion Potion",
                "Divine Battlemage Potion",
                "Divine Magic Potion",
                "Divine Super Combat Potion",
                "Divine Super Combat Potion",
                "Dwarf Weed Potion",
                "Energy Potion",
                "Extended Antifire",
                "Extended Super Antifire"
                "Fishing Potion",
                "Forgotten Brew",
                "Guam Potion",
                "Harralander Potion",
                "Hunter Potion",
                "Irit Potion",
                "Kwuarm Potion",
                "Lantadyme Potion",
                "Magic Potion"
                "Marrentill Potion",
                "Prayer Potion",
                "Ranarr Potion",
                "Ranging Potion",
                "Relicym's Balm (unf)",
                "Relicym's Balm",
                "Restore Potion",
                "Rouge's Purse",
                "Sanfew Serum mix 1",
                "Sanfew Serum mix 2",
                "Sanfew Serum",
                "Saradomin Brew",
                "Serum 207 UNF",
                "Serum 207",
                "Snapdragon Potion",
                "Stamina Potion",
                "Strength Potion",
                "Super AntiPoison",
                "Super Antifire Potion",
                "Super Attack",
                "Super Combat",
                "Super Defence",
                "Super Energy",
                "Super Restore",
                "Super Strength",
                "Tarromin Potion",
                "Toadflax Potion",
                "Tortstol Potion",
                "Weapon Poison++ (unf)",
                "Weapon Poison++",
                "Weapon poison",
                "Zamorak Brew"]
